"""flexible product schema

Revision ID: 927179233531
Revises: 5179285ae0ae
Create Date: 2026-03-17 07:17:58.218711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '927179233531'
down_revision: Union[str, None] = '5179285ae0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('attributes', sa.JSON(), nullable=True))
    op.drop_constraint('uq_product_sku', 'products', type_='unique')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'name_bn')
    op.drop_column('products', 'discount_price')
    op.drop_column('products', 'description')
    op.drop_column('products', 'metadata_extra')
    op.drop_column('products', 'category')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'stock_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('metadata_extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('discount_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('name_bn', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_product_sku', 'products', ['tenant_id', 'sku'])
    op.drop_column('products', 'attributes')
    # ### end Alembic commands ###
